###################################################
# MMORPG 月色之湖大型多人在线角色扮演插件         #
# 作者：Month_Light、Simon、Ni_xiaoqi、Ruiqi_666  #
###################################################

# 插件版本号
version: A-1.3

# 是否开启调试功能
# 如遇到 Bug 可尝试反馈给作者进行修复
Debug: false

# 语言文件的前缀
Prefix: '&3MoonLake &e>> &f'

# 插件用到的语言文件
# 默认文件为 zh_CN.lang 如有其他
# 例如翻译个 en_US.lang 则只需要
# 将此处修改为 en_US 即可 其他同
Language: zh_CN

# 数据库配置
MySQL:

  # 数据库的名称
  Database: moonlake_mmorpg

  # 数据库的地址
  Host: 127.0.0.1

  # 数据库的端口
  Port: 3306

  # 数据库的用户名
  Username: root

  # 数据库的密码
  Password: moonlake

# 玩家默认数据配置
# 也就是首次进入服务器的默认数据
PlayerDefaultData:

  # 默认最大血量
  MaxHealth: 100.0

  # 默认最大魔法
  MaxMagic: 100

  # 默认最大灵魂
  MaxSoul: 10

# 玩家血量配置
PlayerHealth:

  # 血量条标题
  # 可用变量: %health, %maxHealth, %player
  # 变量解释:
  #   %health: 玩家的当前血量
  #   %maxHealth: 玩家的最大血量
  #   %player: 玩家的显示名称
  HealthBarTitle: '玩家您的血量: %health / %maxHealth'

# 玩家魔法配置
PlayerMagic:

  # 魔法条标题
  # 可用变量: %magic, %maxMagic, %player
  # 变量解释:
  #   %magic: 玩家的当前魔法
  #   %maxMagic: 玩家的最大魔法
  #   %player: 玩家的显示名称
  MagicBarTitle: '玩家您的魔法: %magic / %maxMagic'

  # 每多少时间恢复次魔法值 (秒)
  Freq: 1.5

  # 每次恢复的数量
  Amount: 1

# 玩家聊天配置
PlayerChat:

  # 是否开启玩家全局聊天
  # 当为 false 时可以设置下面的附近聊天半径
  GlobalChat: true

  # 聊天格式
  # 可用变量: %role, %level, %player, %message
  # 变量解释:
  #   %role: 玩家的职业前缀
  #   %level: 玩家的当前等级
  #   %player: 玩家的显示名称
  #   %message: 玩家的聊天消息
  ChatFormat: '[%role][Lv%level] %player &e>> &f%message'

  # 是否允许无职业玩家聊天
  NotHaveRolePlayerChat: false

  # 设置玩家的聊天半径
  # 当全局聊天状态为 false 时
  # 玩家聊天位置多少半径内玩家可以看到消息
  NearbyChatRadius: 10

# 玩家列表配置
PlayerList:

  # 是否开启玩家列表名更改
  Enable: true

  # 玩家列表名的格式
  # 可用变量: %role, %player
  # 变量解释:
  #   %role: 玩家的职业前缀
  #   %player: 玩家的显示名称
  Format: '[%role] | %player'

  # 没有职业的玩家列表名格式
  # 可用变量: %player
  # 变量解释:
  #   %player: 玩家的显示名称
  NotRoleFormat: '&7%player'

# 玩家升级配置
PlayerUpgrade:

  # 升级每次获得的技能点
  SkillPoint: 1

  # 当倍数的值大于 1 时玩家等级是 5 的倍数时获得的特殊奖励
  # 如果不开启可以将这里设置为 0 即可
  Multiple: 2

# 玩家仓库配置
PlayerRepertory:

  # 仓库 GUI 的标题
  # 可用变量: %player
  # 变量解释:
  #   %player: 玩家的显示名称
  Title: '【个人仓库】: %player'

  # 默认玩家的个人仓库大小 (1-6)
  Default: 3

  # 权限玩家的个人仓库大小 (1-6)
  # 权限节点: moonlake.mmorpg.repertory
  Permission: 6

# 技能组合配置
SkillCombo:

  # 组合的最大大小
  ComboSize: 3

  # 在多少毫秒内没有下次组合则重置
  ComboTime: 2000

# 技能 GUI 配置
SkillGUI:

  # 技能 GUI 的标题
  # 可用变量: %role, %player
  # 变量解释:
  #   %role: 玩家的职业名
  #   %player: 玩家的显示名称
  Title: '【%role技能面板】: %player'

  # 技能 GUI 的大小,建议不需要修改 (1-6)
  Size: 6

  # 玩家交互完技能 GUI 是否关闭
  Close: false

  # 技能物品标签属性格式
  # 可用 '%^' 来给标签换行
  # 可用变量: %skillName, %skillLevel, %skillMagic, %skillCombo, %skillDesc, %skillReqAtt
  # 变量解释:
  #   %skillName: 技能的显示名
  #   %skillLevel: 技能的当前等级
  #   %skillMagic: 技能的消耗魔法值
  #   %skillCombo: 技能的的组合触发键
  #   %skillDesc: 技能的信息介绍等
  #   %skillReqAtt: 技能的需求属性
  SkillItemLoreAtt:
    - ''
    - '&7技能名: &b%skillName'
    - ''
    - '&7魔法耗费: &9%skillMagic'
    - '&7当前等级: &a%skillLevel'
    - '&7技能组合键: &c%skillCombo'
    - ''
    - '&7技能需求: &a%skillReqAtt'
    - ''
    - '&2&o%skillDesc'

  # 技能点物品名称属性格式
  # 可用变量: %skillPoint
  # 变量解释:
  #   %skillPoint: 该玩家的技能点数
  SkillPointItemNameAtt: '&2您拥有:> &d%skillPoint &2技能点'

# 区域配置
Region:

  # 区域默认进入消息
  # 可用变量: %region, %player
  # 变量解释:
  #   %region: 区域的名称
  #   %player: 进入的玩家
  EnterDefault: '欢迎来到 %region 区域'

  # 区域默认离开消息
  # 可用变量: %region, %player
  # 变量解释:
  #   %region: 区域的名称
  #   %player: 进入的玩家
  LeaveDefault: '恭送 %player 旅途愉快'

# 玩家坐骑配置
PlayerMount:

  # 玩家召唤坐骑后的冷却时间 (秒)
  CoolDown: 30

  # 坐骑名称修改的允许长度
  DisplayNameLength: 16

  # 坐骑 GUI 的标题
  # 可用变量: %player
  # 变量解释:
  #   %player: 玩家的显示名称
  Title: '【坐骑仓库】: %player'

# 传送书配置
TpBook:

  # 是否开启传送失明效果
  Blindness: true

  # 玩家传送的等待延迟 (Tick)
  Delay: 100

  # 是否开启附近有怪物时无法使用传送书
  # 此值如果为 0 则不开启 (半径)
  CheckNearbyMob: 5

# 怪物配置
Mob:

  # 是否开启怪物死亡显示全息信息
  DeathShowHologramInfoState: true

  # 怪物死亡显示的全息信息
  # 可用变量: %exp, %player
  # 变量解释:
  #   %exp: 怪物的掉落经验
  #   %player: 击杀怪物的玩家名
  DeathShowHologramInfo: '&e+%exp EXP &f击杀者: &c%player'

  # 显示的全息信息持续的时间 (秒)
  DeathShowHologramInfoTime: 2

